chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path("message/<str:username>/", views.start_conversation, name="start-convo"),
    path(
        "conversation/<int:conversation_id>/", views.conversation, name="conversation"
    ),
    path("conversations/", views.conversations, name="conversations"),
]

dog/urls.py
from django.urls import path
from . import views

app_name = "dog"
urlpatterns = [
    path("list/", views.dog_list, name='list'), # 첫번째 URL패턴
    path("dog/profile/<int:user_id>/", views.dog_profile_view, name="profile"),
]

friendship/urls.py
from django.urls import path
from friendship import views


app_name = "friendship"
urlpatterns = [
    path("friends/", views.friends, name="friendship"),
    path("<str:username>/accept", views.accept_request, name="accept-request"),
    path("<str:username>/reject", views.reject_request, name="reject-request"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/update/", views.profile_update, name="profile_update"),
    path("dog/update/", views.dog_update, name="dog_update"),
]

chat/models.py
from django.db import models

from users.models import MyUser


# Create your models here.


class Conversation(models.Model):
    initiator = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, related_name="convo_starter"
    )
    receiver = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, related_name="convo_participant"
    )
    timestamp = models.DateTimeField(auto_now_add=True)


class Message(models.Model):
    sender = models.ForeignKey(
        MyUser, on_delete=models.PROTECT, related_name="message_sender"
    )
    receiver = models.ForeignKey(
        MyUser, on_delete=models.PROTECT, related_name="message_receiver"
    )
    text = models.CharField(max_length=200)
    attachment = models.ImageField(blank=True)
    conversation_id = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    timestamp = models.DateTimeField()

chat/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Max
from django.db.models.functions import Coalesce
from django.shortcuts import redirect, reverse, render

from friendship.models import Friendship
from users.models import MyUser
from .models import Conversation


# Create your views here.


@login_required
def start_conversation(request, username):
    participant = MyUser.objects.get(username=username)

    # Checks if the user exists or not
    if participant:
        friendship = Friendship.objects.filter(
            Q(user=request.user, friend=participant, status=1)
            | Q(user=participant, friend=request.user, status=1)
        )

        # checks if the logged in user and requested user are friends
        if friendship.exists():
            _conversation = Conversation.objects.filter(
                Q(initiator=request.user, receiver=participant)
                | Q(initiator=participant, receiver=request.user)
            )

            #  checks if a conversation has already begun
            if not _conversation.exists():
                new_convo = Conversation.objects.create(
                    initiator=request.user, receiver=participant
                )
                return redirect(reverse("chat:conversation", args=(new_convo.id,)))

            # redirects to the conversation that already exists
            return redirect(reverse("chat:conversation", args=(_conversation[0].id,)))

        # displays a message that the two users are not friends
        messages.warning(
            request, "Action cannot be completed because you are not friends"
        )
        return redirect(reverse("friendship:friendship"))

    # user doesn't exist
    messages.error(request, "User does not exist")
    return redirect(reverse("friendship:friendship"))


@login_required
def conversation(request, conversation_id):
    convo = Conversation.objects.filter(id=conversation_id)
    if not convo.exists():
        messages.warning(request, "Conversation does not exist")
        return redirect(reverse("friendship:friendship"))
    return render(
        request, "chat/room.html", {"conversation": convo[0], "title": "Conversation"}
    )


@login_required
def conversations(request):
    convo = (
        Conversation.objects.filter(
            Q(initiator=request.user) | Q(receiver=request.user)
        )
        .annotate(last_message_sent=Coalesce(Max("message__timestamp"), "timestamp"))
        .order_by("-last_message_sent")
    )
    return render(
        request, "chat/chat.html", {"conversations": convo, "title": "Conversations"}
    )

chat/templates/chat/chat.html
{% extends 'main/layout.html' %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/theme.css' %}">
{% endblock head %}
{% block content %}
    <nav class="nav nav-tabs justify-content-around">
        <a class="nav-item nav-link h3" href="{% url 'dog:list' %}">
            <span class="d-none d-sm-inline">동네 견주</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-binoculars" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3 active" href="{% url 'chat:conversations' %}">
            <span class="d-none d-sm-inline">메세지</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-right-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2 1h12a1 1 0 0 1 1 1v11.586l-2-2A2 2 0 0 0 11.586 11H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                <path fill-rule="evenodd" d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'friendship:friendship' %}">
            <span class="d-none d-sm-inline">산책 메이트</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM1.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm4.5 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M13 7.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'users:profile' %}" >
            <span class="d-none d-sm-inline">프로필</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
            </svg>
        </a>
    </nav>
    {% if conversations.all|length > 0 %}
        {% for conversation in conversations %}
            {% if conversation.message_set.all|length > 0 %}
                {% if conversation.initiator.username == user.username %}
                    <div class="d-flex justify-content-around mt-2">
                        <div>
                            <img src="{{ conversation.receiver.avatar }}" alt="user profile" class="img-fluid">
                        </div>
                        <div>
                            <div class="align-self-start">
                                {{ conversation.receiver.username }}
                            </div>
                            <div class="align-self-end">
                                    <a href="{% url 'chat:conversation' conversation.id %}">
					{% if conversation.message_set.last.text|length > 0 %}
                                        	{{ conversation.message_set.last.text|truncatechars:5 }}
                                    	{% else %}
                                        	Image
                                    	{% endif %}
                                    </a>
                            </div>
                        </div>
                        <div>
                            <small class="convo-info-time">{{ conversation.message_set.last.timestamp|date:"c" }}</small>
                        </div>
                    </div>
                    <hr>
                {% else %}
                    <div class="d-flex justify-content-around mt-4">
                        <div>
                            <img src="{{ conversation.initiator.avatar }}" alt="user profile" class="img-fluid">
                        </div>
                        <div>
                            <div class="align-self-start">
                                {{ conversation.initiator.username }}
                            </div>
                            <div class="align-self-end">
                                <a href="{% url 'chat:conversation' conversation.id %}">
                                    {% if conversation.message_set.last.text|length > 0 %}
                                        {{ conversation.message_set.last.text|truncatechars:5 }}
                                    {% else %}
                                        Image
                                    {% endif %}
                                </a>
                            </div>
                        </div>
                        <div>
                            <small class="convo-info-time">{{ conversation.message_set.last.timestamp|date:"c" }}</small>
                        </div>
                    </div>
                    <hr>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% else %}
        <div class="container-fluid">
        <h2 class="text-center mt-5 mb-5">아직 대화중인 메이트가 없어요!</h2>
            <a class="btn btn-info btn-block btn-lg" role="button" href="{% url 'friendship:friendship' %}">대화 시작</a>
        </div>
    {% endif %}
{% endblock content %}
{% block scripts %}
    <script>
        const dates = document.querySelectorAll('.convo-info-time')
        dates.forEach(el => {
            let time = el.textContent
            el.textContent = moment(time).fromNow()
        });
    </script>
{% endblock scripts %}

chat/templates/chat/room.html
{% extends 'main/chat_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'chat/chat.css' %}">
{% endblock head %}

{% block content %}
<section class="msger">
    <header class="msger-header">
        <div class="msger-header-title">
            <a href="{% url 'chat:conversations' %}" class="hide-line">
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M5.854 4.646a.5.5 0 0 1 0 .708L3.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0z"/>
                    <path fill-rule="evenodd" d="M2.5 8a.5.5 0 0 1 .5-.5h10.5a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                </svg>
            </a>
            {% if conversation.initiator.username == user.username %}
                <img src="{{ conversation.receiver.avatar }}" alt="">
                {{ conversation.receiver.username }}
            {% else %}
                <img src="{{ conversation.initiator.avatar }}" alt="">
                {{ conversation.initiator.username }}
            {% endif %}
        </div>
    </header>


    <main class="msger-chat">
        {% for message in conversation.message_set.all %}
            {% if message.sender.username == user.username %}
                <div class="msg right-msg">
                    <div class="msg-img" style="background-image: url({{ message.sender.avatar }})"></div>
                    <div class="msg-bubble">
                        <div class="msg-info">
                            <div class="msg-info-name">{{ message.sender.username }}</div>
                            <div class="msg-info-time">{{ message.timestamp|date:"c" }}</div>
                        </div>
                        <div class="msg-text">
                            {{ message.text }}
                        </div>
                        {% if message.attachment %}
                            <img src="{{ message.attachment.url }}" alt="attachment">
                        {% endif %}
                    </div>
                </div>
            {% else %}
                <div class="msg left-msg">
                    <div class="msg-img" style="background-image: url({{ message.sender.avatar }})"></div>
                    <div class="msg-bubble">
                        <div class="msg-info">
                            <div class="msg-info-name">{{ message.sender.username }}</div>
                            <div class="msg-info-time">{{ message.timestamp|date:"c" }}</div>
                        </div>
                        <div class="msg-text">
                            {{ message.text }}
                        </div>
                        {% if message.attachment %}
                            <img src="{{ message.attachment.url }}" alt="attachment">
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}

    </main>
    {{ conversation.id|json_script:"room-name" }}

    <form class="msger-inputarea">
        <input type="text" class="msger-input" placeholder="Enter your message...">
        <label for="image-input">
            <i class="fas fa-camera fa-500px"></i>
        </label>
        <input type="file" onchange="previewFile()" id="image-input" class="d-none" accept=".png, .jpg, .jpeg">
        <button type="submit" class="msger-send-btn">Send</button>
    </form>
</section>
{% endblock content %}

{% block scripts %}
    <script>
    // for now it only works for one image
    const get = (selector, root = document) => root.querySelector(selector);

    let attachment; //the image attached

    // Uses moment to format the dates. Still of how to do this without reloading the page.
    const dates = document.querySelectorAll('.msg-info-time')
    dates.forEach(el => {
        let time = el.textContent
        el.textContent = moment(time).fromNow()
    })

    // The currently logged in user
    const currentUserImg = "{{ user.avatar }}";
    const currentUserName = "{{ user.username }}";

    // The other party in the conversation
    {% if conversation.initiator.username == user.username %}
        const recipientImg = "{{ conversation.receiver.avatar }}";
        const recipientUserName = "{{ conversation.receiver.username }}";
    {% else %}
        const recipientImg = "{{ conversation.initiator.avatar }}";
        const recipientUserName = "{{ conversation.initiator.username }}";
    {% endif %}

    const msgForm = get(".msger-inputarea");
    const msgInput = get(".msger-input");
    const msgChat = get(".msger-chat");
    const roomName = JSON.parse(get("#room-name").textContent);
    const chatSocket = new WebSocket(
        'wss://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    // Focus on the input tag and scroll to the bottom
    msgInput.focus();
    msgChat.scrollTop = msgChat.scrollHeight;
    // End

    chatSocket.onmessage = e => {
        const data = JSON.parse(e.data);
        if(data.hasOwnProperty('attachment')){
            if (data.sender === recipientUserName) {
                appendMessage(recipientUserName, recipientImg, 'left', data.message, data.time, data.attachment)
            }else{
                appendMessage(currentUserName, currentUserImg, 'right', data.message, data.time, data.attachment)
            }
        }else{
            if (data.sender === recipientUserName) {
                appendMessage(recipientUserName, recipientImg, 'left', data.message, data.time)
            }else{
                appendMessage(currentUserName, currentUserImg, 'right', data.message, data.time)
            }
        }
    };

    chatSocket.onclose = e => console.error(e);

    // the function that grabs the image and converts to base64
    const previewFile = () => {
        const file = document.querySelector('input[type=file]').files[0];
	var img = document.createElement("img");
        const reader = new FileReader();
        reader.addEventListener("load", () => {
           img.src = reader.result;
           img.onload = function() {
	        var canvas = document.createElement('canvas');
                var ctx = canvas.getContext('2d');
                canvas.width = 300;
                canvas.height = canvas.width * (img.height / img.width);
                ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

                // SEND THIS DATA TO WHEREVER YOU NEED IT
                var data = canvas.toDataURL('image/png');
		
		// convert image file to base64 string
                attachment = {
                     format: data.split(',')[0].split('/')[1].split(';')[0],
                     data: data.replace(/^data:.+;base64,/, '')
                }

           }
        }, false);

        if (file) {
            reader.readAsDataURL(file);
        }
    }

    msgForm.addEventListener("submit", event => {
        event.preventDefault();

        let message;
        const msgText = msgInput.value;

        // checks if both message and attachment are empty
        if(!msgText && !attachment){

            msgInput.value = "Attachment and message cannot be empty!"
            setTimeout(()=>{
                msgInput.value = "";
            }, 1000);

        }else{
            message = JSON.stringify({
                'message': msgText,
                {% if conversation.initiator.username == user.username %}
                    'recepient': "{{ conversation.receiver.username }}",
                {% else %}
                    'recepient': "{{ conversation.initiator.username }}",
                {% endif %}
                    'sender': "{{ user.username }}",
                    attachment,
                    'time': Date.now()
            });
            chatSocket.send(message);
            msgInput.value = "";
        }
    });

    const appendMessage = (name, img, side, text, timestamp, url=undefined) => {
        let msgHTML;
        if (url){
            msgHTML = `
                <div class="msg ${side}-msg">
                <div class="msg-img" style="background-image: url(${img})"></div>

                <div class="msg-bubble">
                <div class="msg-info">
                <div class="msg-info-name">${name}</div>
                <div class="msg-info-time">${moment.utc(timestamp).fromNow()}</div>
                </div>

                <div class="msg-text">${text}</div>
                <img src=${url} alt="attachment">
                </div>
                </div>
                `;
        }else{
            msgHTML = `
                <div class="msg ${side}-msg">
                <div class="msg-img" style="background-image: url(${img})"></div>

                <div class="msg-bubble">
                <div class="msg-info">
                <div class="msg-info-name">${name}</div>
                <div class="msg-info-time">${moment.utc(timestamp).fromNow()}</div>
                </div>

                <div class="msg-text">${text}</div>
                </div>
                </div>
                `;
        }
        msgChat.insertAdjacentHTML("beforeend", msgHTML);
        msgChat.scrollTop = msgChat.scrollHeight;
    }
    </script>
{% endblock scripts %}