chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path("message/<str:username>/", views.start_conversation, name="start-convo"),
    path(
        "conversation/<int:conversation_id>/", views.conversation, name="conversation"
    ),
    path("conversations/", views.conversations, name="conversations"),
]

dog/urls.py
from django.urls import path
from . import views

app_name = "dog"
urlpatterns = [
    path("list/", views.dog_list, name='list'), # 첫번째 URL패턴
    path("dog/profile/<int:user_id>/", views.dog_profile_view, name="profile"),
]

friendship/urls.py
from django.urls import path
from friendship import views


app_name = "friendship"
urlpatterns = [
    path("friends/", views.friends, name="friendship"),
    path("<str:username>/accept", views.accept_request, name="accept-request"),
    path("<str:username>/reject", views.reject_request, name="reject-request"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/update/", views.profile_update, name="profile_update"),
    path("dog/update/", views.dog_update, name="dog_update"),
]

friendship/models.py
from django.db import models

from users.models import MyUser


# Create your models here.


class Friendship(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="sender")
    friend = models.ForeignKey(
        MyUser, on_delete=models.CASCADE, related_name="receiver"
    )
    status = models.PositiveSmallIntegerField(
        verbose_name="friendship status",
        default=0,
        help_text="0: Pending, 1: Accepted, 2: Rejected",
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Friendship_{self.user.username}_{self.friend.username}"

    @staticmethod
    def friends(user):
        friends = []
        for _ in Friendship.objects.filter(user=user, status=1):
            friends.append({"username": _.friend.username, "gravatar": _.friend.avatar})
        for _ in Friendship.objects.filter(friend=user, status=1):
            friends.append({"username": _.user.username, "gravatar": _.user.avatar})

        return friends

    @staticmethod
    def pending_requests(user):
        requests = []
        for _ in Friendship.objects.filter(friend=user, status=0):
            requests.append({"username": _.user.username, "gravatar": _.user.avatar})

        return requests

friendship/forms.py
from django import forms

from users.models import MyUser


class AddFriendForm(forms.Form):
    username = forms.CharField(label = "요청을 보낼 견주의 이름을 입력하세요.", max_length=30)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

    def clean_username(self):
        if not MyUser.objects.filter(

            username=self.cleaned_data.get("username")
        ).exists():
            raise forms.ValidationError("Username does not exist")

        if self.user.username == self.cleaned_data.get("username"):
            raise forms.ValidationError("You cannot add yourself")

        return self.cleaned_data.get("username")

friendship/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, reverse

from .forms import AddFriendForm
from .models import Friendship
from users.models import MyUser


@login_required
def friends(request):
    form = AddFriendForm(user=request.user)
    if request.method == "POST":
        form = AddFriendForm(request.POST, user=request.user)
        if form.is_valid():
            new_friend = MyUser.objects.get(username=form.cleaned_data.get("username"))
            current_user = request.user

            # checks if there is a pending request yet to be accepted.
            if (
                Friendship.objects.filter(user=new_friend, friend=current_user).count()
                > 0
            ):
                messages.warning(
                    request,
                    "You have a pending request or already rejected a request from this user",
                )
                return redirect(reverse("friendship:friendship"))

            # checks if the two users are friends already
            if Friendship.objects.filter(
                Q(user=current_user, friend=new_friend, status=1)
                | Q(user=new_friend, friend=current_user, status=1)
            ):
                messages.info(request, "You are already friends with this user")
                return redirect(reverse("friendship:friendship"))

            if Friendship.objects.filter(
                user=current_user, friend=new_friend, status=0
            ):
                messages.info(request, "You already sent a friend request to this user")
                return redirect(reverse("friendship:friendship"))

            # a success message
            Friendship.objects.create(user=current_user, friend=new_friend)
            messages.success(request, "Friend request sent successfully")
            return redirect(reverse("friendship:friendship"))

    return render(
        request,
        "friendship/friends.html",
        {
            "form": form,
            "title": "Friends",
            "friends": Friendship.friends(request.user),
            "requests": Friendship.pending_requests(request.user),
        },
    )


@login_required
def accept_request(request, username):
    friend = MyUser.objects.get(username=username)
    if friend:
        is_friendship_exists = Friendship.objects.get(
            user=friend, friend=request.user, status=0
        )
        if is_friendship_exists:
            friendship = Friendship.objects.get(
                user=friend, friend=request.user, status=0
            )
            friendship.status = 1
            friendship.save()

            messages.success(request, "Friend request accepted")
            return redirect(reverse("friendship:friendship"))

        messages.warning(request, "There is no request from this user")
        return redirect(reverse("friendship:friendship"))

    messages.error(request, "No account with such username exists")
    return redirect(reverse("friendship:friendship"))


@login_required
def reject_request(request, username):
    friend = MyUser.objects.get(username=username)
    if friend:
        is_friendship_exists = Friendship.objects.get(
            user=friend, friend=request.user, status=0
        )
        if is_friendship_exists:
            friendship = Friendship.objects.get(
                user=friend, friend=request.user, status=0
            )
            friendship.status = 2
            friendship.save()

            messages.success(request, "Friend request rejected")
            return redirect(reverse("friendship:friendship"))

        messages.warning(request, "There is no request from this user")
        return redirect(reverse("friendship:friendship"))

    messages.error(request, "No account with such username exists")
    return redirect(reverse("friendship:friendship"))

friendship/templates/friendship/friends.html
{% extends 'main/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
<!--    <link rel="stylesheet" type="text/css" href="{% static 'friendship/friendship.css' %}">-->
    <link rel="stylesheet" href="{% static 'users/css/theme.css' %}">
{% endblock head %}

{% block content %}
    <nav class="nav nav-tabs justify-content-around">
        <a class="nav-item nav-link h3" href="{% url 'dog:list' %}">
            <span class="d-none d-sm-inline">동네 견주</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-binoculars" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'chat:conversations' %}">
            <span class="d-none d-sm-inline">메세지</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-right-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2 1h12a1 1 0 0 1 1 1v11.586l-2-2A2 2 0 0 0 11.586 11H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                <path fill-rule="evenodd" d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3 active" href="{% url 'friendship:friendship' %}">
            <span class="d-none d-sm-inline">산책 메이트</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM1.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm4.5 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M13 7.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'users:profile' %}" >
            <span class="d-none d-sm-inline">프로필</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
            </svg>
        </a>
    </nav>
    <div id="accordion" class="myaccordion">
    <div class="card">
        <div class="card-header" id="headingTwo">
            <h2 class="mb-0">
                <button class="d-flex align-items-center justify-content-between btn btn-block collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                산책 메이트 ({{ friends|length }})
                <span class="fa-stack">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fas fa-plus fa-stack-1x fa-inverse"></i>
                </span>
                </button>
            </h2>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
                {% for friend in friends %}
                    <div class="d-flex justify-content-between mb-4">
                        <div>
                            <img src="{{ friend.gravatar }}" alt="friend profile" class="img-fluid">
                            <span class="px-2">{{ friend.username }}</span>
                        </div>
                        <div class="remove-dash">
                            <a href="{% url 'chat:start-convo' friend.username %}">
                                <i class="far fa-envelope fa-2x text-success"></i>
                            </a>
                            <a href="#" class="px-2 text-danger" style="">
                                <i class="fas fa-ban fa-2x"></i>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" id="headingThree">
            <h2 class="mb-0">
                <button class="d-flex align-items-center justify-content-between btn btn-block collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                받은 요청 ({{ requests|length }})
                <span class="fa-stack">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fas fa-plus fa-stack-1x fa-inverse"></i>
                </span>
                </button>
            </h2>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
                {% for friend in requests %}
                    <div class="d-flex justify-content-between">
                        <div>
                            <img src="{{ friend.gravatar }}" alt="friend profile" class="img-fluid">
                            <span class="px-2">{{ friend.username }}</span>
                        </div>
                        <div class="remove-dash">
                            <a href="{% url 'friendship:accept-request' friend.username %}" class="text-success">
                                <i class="fas fa-check fa-2x"></i>
                            </a>
                            <a href="{% url 'friendship:reject-request' friend.username %}" class="px-2 text-danger" style="">
                                <i class="fas fa-times fa-2x"></i>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
    <div class="container">
        <form action="{% url 'friendship:friendship' %}" method="post" class="mt-5 ">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary btn-block">요청보내기</button>
        </form>
    </div>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'friendship/friendship.js' %}"></script>
{% endblock %}