blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("blog/", views.blog_home, name='home'), # 첫번째 URL패턴
    path("blog/post/<int:post_id>/", views.blog_post_view, name="post"),
    path("blog/post-delete/<int:post_id>/", views.blog_post_delete, name="delete"),
    path("blog/post-edit/<int:post_id>/", views.blog_post_edit, name="edit"),
    path("blog/post-create/", views.blog_post_create, name="create"),
]

chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path("message/<str:username>/", views.start_conversation, name="start-convo"),
    path(
        "conversation/<int:conversation_id>/", views.conversation, name="conversation"
    ),
    path("conversations/", views.conversations, name="conversations"),
]

dog/urls.py
from django.urls import path
from . import views

app_name = "dog"
urlpatterns = [
    path("list/", views.dog_list, name='list'), # 첫번째 URL패턴
    path("dog/profile/<int:user_id>/", views.dog_profile_view, name="profile"),
]

friendship/urls.py
from django.urls import path
from friendship import views


app_name = "friendship"
urlpatterns = [
    path("friends/", views.friends, name="friendship"),
    path("<str:username>/accept", views.accept_request, name="accept-request"),
    path("<str:username>/reject", views.reject_request, name="reject-request"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("profile/update/", views.profile_update, name="profile_update"),
    path("dog/update/", views.dog_update, name="dog_update"),
]

users/models.py
from hashlib import md5
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, AbstractUser
from django.core.validators import EmailValidator
from django.db import models
from django.utils import timezone
from .choice import *

class MyUserManager(BaseUserManager):
    def _create_user(self, username, email, address, password):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("이메일은 반드시 입력해야합니다.")
        if not username:
            raise ValueError("이름을 입력해주세요.")

        user = self.model(
            username=self.model.normalize_username(username),
            email=self.normalize_email(email),
            address=address,
            password=password,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, address, password=None):
        return self._create_user(username, email, address, password)

    def create_superuser(self, email, username, address, password=None):
        user = self.create_user(email, username, address, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


# models.Model 일반적인 모델 정보로 바꾸기, 1:1 매칭
class MyUser(AbstractBaseUser):
    email = models.EmailField(unique=True,validators=[EmailValidator()])
    username = models.CharField(unique=True,max_length=30)
    address = models.CharField(max_length=200)

    is_active = models.BooleanField(
        "active",
        default=True,
        help_text="Designates whether this user should be treated as active. "
        "Unselect this instead of deleting accounts.",
    )
    is_admin = models.BooleanField(
        "admin status",
        default=False,
        help_text="Designates whether the user can log into this admin site.",
    )
    date_joined = models.DateTimeField("date joined", default=timezone.now)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "address"]

    def __str__(self):
        return self.email

    @property
    def avatar(self):
        digest = md5(self.email.lower().encode("utf-8")).hexdigest()
        return "https://www.gravatar.com/avatar/{}?d=identicon&s=64".format(digest)

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"


class Dog(models.Model):
    owner = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    dog_name = models.CharField(verbose_name="Dog Name", max_length=18, null=False)
    dog_age = models.IntegerField(verbose_name="Dog Age", null=False, default='0')
    dog_breed = models.CharField(choices=BREED_CHOICES, max_length=18, verbose_name="Dog Breed", null=False)
    dog_gender = models.CharField(choices=DOG_GENDER_CHOICES, max_length=18, verbose_name="Dog Gender", null=False)
    size = models.CharField(choices=SIZE_CHOICES, max_length=10, verbose_name="Dog Size", null=False)


# class Area(models.Model):
#     username = models.ForeignKey(MyUser, on_delete=models.CASCADE, null=True)
#     sido = models.CharField(verbose_name="시도", max_length=10)
#     sigungu = models.CharField(verbose_name="시군구", max_length=10)
#     bname = models.CharField(verbose_name="동이름", max_length=10)


class MyUserProfile(models.Model):
    username = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    bio = models.TextField(null=True)
    walking_count = models.IntegerField(null=True)
    walking_time = models.IntegerField(null=True)
    manner = models.IntegerField(null=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from .models import *
from .choice import *
from django.forms.widgets import DateInput


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput,
        min_length=6,
    )
    password2 = forms.CharField(
        label="비밀번호 확인",
        widget=forms.PasswordInput,
        min_length=6,
    )

    class Meta:
        model = MyUser
        fields = ("email", "username", "address")

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("비밀번호가 일치하지 않습니다.")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = (
            "email",
            "username",
            "address",
        )

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', }),
        error_messages={'required': '아이디을 입력해주세요.'},
        max_length=17,
        label='이메일'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', }),
        error_messages={'required': '비밀번호를 입력해주세요.'},
        label='비밀번호'
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            try:
                user = MyUser.objects.get(username=username)
            except MyUser.DoesNotExist:
                self.add_error('username', '아이디가 존재하지 않습니다.')
                return

            if not check_password(password, user.password):
                self.add_error('password', '비밀번호가 틀렸습니다.')


class DogCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    dog_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', }),
        error_messages={'required': '아이디을 입력해주세요.'},
        max_length=17,
        label="강아지 이름"
    )

    dog_age = forms.IntegerField(
        error_messages={'required': '나이를 입력해주세요.'},
        label="강아지 나이"
    )

    dog_bread = forms.ChoiceField(choices=BREED_CHOICES,
        label="견종",
        widget=forms.Select(
            attrs={'class': 'form-control',}),
    )
    dog_gender = forms.ChoiceField(choices=DOG_GENDER_CHOICES,
        label="강아지 성별",
        widget=forms.Select(
            attrs={'class': 'form-control', }),
    )

    size = forms.ChoiceField(choices=SIZE_CHOICES,
        label="사이즈",
        widget=forms.Select(
            attrs={'class': 'form-control',}),
    )


    class Meta:
        model = Dog
        fields = ("dog_name", "dog_age", "dog_bread", "dog_gender", "size")

    def save(self, commit=True):
        # Save the provided password in hashed format
        dog = super(DogCreationForm, self).save(commit=False)
        if commit:
            dog.save()

        return dog

users/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import PermissionDenied
# from .forms import CsRegisterForm
from django.views.generic import CreateView


from .forms import *
from blog.models import *
from users.models import *

# Create your views here.


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, "회원가입이 완료되었습니다.")
            return redirect(reverse("users:login"))
    return render(
        request, "users/register.html", {"title": "Create Account", "form": form}
    )


@login_required
def profile(request, ):
    myprofile = MyUserProfile.objects.filter(username=request.user.id).order_by("-pk")
    dog = Dog.objects.filter(owner=request.user.id).order_by("-pk")
    review_list = DogReview.objects.all().order_by("-pk")
    post_list = Post.objects.filter(author=request.user.id).order_by("-pk")
    context = {
        "post_list": post_list,
        "myprofile": myprofile,
        "review_list": review_list,
        "dog": dog,
        "avatar": request.user.avatar,
    }
    if request.method == "GET":
        return render(
            request,
            "users/profile.html",
            context,
        )
    elif request.method == "POST":
            new_review = DogReview()
            new_review.author = request.user
            new_review.review = request.POST["review"]
            new_review.save()
            return HttpResponseRedirect(reverse("users:profile"))

@login_required
def profile_update(request):
    user = request.user
    user = MyUser.objects.filter(username=user)
    user_info = MyUserProfile.objects.filter(username=user)
    if request.method == "GET":
        context = {
            "user": user,
            "user_info": user_info,
            "avatar": request.user.avatar,
    }
        return render(
        request,
        "users/profile_update.html",
        context,
    )
    elif request.method == "POST":
        user.name = request.POST["title"]
        user_info.text = request.POST["text"]
        user_info.save()
        return HttpResponseRedirect(f"/blog/post/{post_id}/")


class UserLoginView(LoginView, SuccessMessageMixin):
    template_name = "users/login.html"
    extra_context = {"title": "Log In"}
    redirect_authenticated_user = True
    success_message = "로그인 성공"


class UserLogoutView(LogoutView, SuccessMessageMixin):
    template_name = "users/logout.html"
    success_message = "로그아웃 완료"


def dog_update(request):
    form = DogCreationForm()
    if request.method == "POST":
        form = DogCreationForm(request.POST)
        if form.is_valid():
            my_dog = form.save(commit=False)
            my_dog.owner = request.user
            my_dog.created_date = timezone.now()
            my_dog.save()
            messages.success(request, "정보가 저장되었습니다.")
            return redirect(reverse("users:profile"))
    return render(
        request, "users/dog_update.html", {"title": "댕고 | 강아지 정보", "form": form}
    )

users/templates/users/dog_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load crispy_forms_tags %}
    <link rel="stylesheet" href="{% static 'users/css/theme.css' %}">
    <meta charset="UTF-8">
    <title>댕고 | 프로필 수정</title>
</head>
<body>

    <div class="card">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:profile_update' %}">내 정보</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="true" href="{% url 'users:dog_update' %}">강아지 정보</a>
      </li>
    </ul>
  </div>
      <!-- Container fluid -->
      <div class="container-fluid px-6 py-4 bg-light">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-12">
            <!-- Page header -->
            <div>
              <div class="border-bottom pb-4 mb-4 d-flex align-items-center
                  justify-content-between">
                <div class="mb-2 mb-lg-0">
                  <h3 class="mb-0 fw-bold">강아지 정보</h3>
                </div>
                <div>
                  <a href="{% url 'users:profile' %}" class="btn btn-primary">뒤로가기</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row mb-8">
          <div class="col-xl-3 col-lg-4 col-md-12 col-12">
            <div class="mb-4 mb-lg-0">
              <h4 class="mb-1">강아지 정보 수정</h4>
              <p class="mb-0 fs-5 text-muted">강아지 정보를 수정합니다.</p>
            </div>

          </div>

          <div class="col-xl-9 col-lg-8 col-md-12 col-12">
            <!-- card -->
            <div class="card">
              <!-- card body -->
              <div class="card-body">
                <div class=" mb-6">
                  <h4 class="mb-1">강아지 정보 수정</h4>

                </div>
                  <div class="mb-6">
                    <h4 class="mb-1">기본 정보</h4>
                  </div>
                    <form action="{% url 'users:dog_update' %}" method="post" class="mt-5 ">
                    {% csrf_token %}
                    <!-- row -->

                    {{ form|crispy }}

                    <!-- row -->

                      <div class="offset-md-4 col-md-8 mt-4">
                        <button type="submit" class="btn btn-primary"> 강아지 정보 저장 </button>
                      </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</body>
</html>

users/templates/users/logout.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="text-center" style="margin-top: 180px!important;">
        <h1 class="display-4">또 오세요~</h1>
        <p class="lead"><a href="{% url 'users:login' %}">다시 로그인하기</a></p>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'main/layout.html' %}
{% block title %}댕고 | 프로필{% endblock title %}
{% block head %}
	{% load static %}
    <link rel="stylesheet" href="{% static 'users/css/theme.css' %}">
{% endblock head %}
{% block content %}
    <nav class="nav nav-tabs justify-content-around">
        <a class="nav-item nav-link h3" href="{% url 'dog:list' %}">
            <span class="d-none d-sm-inline">동네 견주</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-binoculars" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'chat:conversations' %}">
            <span class="d-none d-sm-inline">메세지</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-right-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2 1h12a1 1 0 0 1 1 1v11.586l-2-2A2 2 0 0 0 11.586 11H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                <path fill-rule="evenodd" d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'friendship:friendship' %}">
            <span class="d-none d-sm-inline">산책 메이트</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM1.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm4.5 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M13 7.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3 active" href="{% url 'users:profile' %}" >
            <span class="d-none d-sm-inline">프로필</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
            </svg>
        </a>
    </nav>
        <!-- Container fluid -->
        <div class="container-fluid px-6 py-4">
          <div class="row align-items-center">
            <div class="col-xl-12 col-lg-12 col-md-12 col-12">
              <!-- Bg -->
              <div class="pt-20 rounded-top" style="background:
                  url({% static 'users/img/profile-cover.jpg' %}) no-repeat;
                  background-size: cover;">
              </div>
              <div class="bg-white rounded-bottom smooth-shadow-sm ">
                <div class="d-flex align-items-center justify-content-between
                    pt-4 pb-6 px-4">
                  <div class="d-flex align-items-center">
                    <!-- avatar -->
                    <div class="avatar-xxl avatar-indicators avatar-online me-2
                        position-relative d-flex justify-content-end
                        align-items-end mt-n10">
                      <img src="{{ user.avatar }}" class="avatar-xxl
                          rounded-circle border border-4 border-white-color-40" alt="">
                      <a href="#!" class="position-absolute top-0 right-0 me-2" data-bs-toggle="tooltip" data-placement="top" title="" data-original-title="Verified">
                        <img src="{% static 'users/img/checked-mark.svg' %}" alt="" height="30" width="30">
                      </a>
                    </div>
                    <!-- text -->
                    <div class="lh-1">
                      <h2 class="mb-0">{{ user.username }}
                        <a href="#!" class="text-decoration-none" data-bs-toggle="tooltip" data-placement="top" title="" data-original-title="Beginner">

                        </a>
                      </h2>
                      <p class="mb-0 d-block">@dango.life</p>
                    </div>
                  </div>
                  <div><a href="{% url 'blog:create' %}" class="btn btn-outline-danger btn-sm d-block mb-1">포스팅</a>
                    <a href="{% url 'users:profile_update' %}" class="btn btn-outline-primary btn-sm d-block">프로필 수정</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- content -->
          <div class="py-6">
            <!-- row -->
            <div class="row">
              <div class="col-12 mb-6">
                <!-- card -->
                <div class="card">
                  <!-- card body -->
                  <div class="card-body">
                    <!-- card title -->
                    <h4 class="card-title mb-4">About Me</h4>
                    <span class="text-uppercase fw-medium text-dark
                        fs-5 ls-2">소개</span>
                    <!-- text -->
                    <p class="mt-2 mb-6">안녕하세요. 환영합니다.</p>
                    <!-- row -->
                    <div class="row">
                      <div class="col-12 mb-5">
                        <!-- text -->
                        <h6 class="text-uppercase fs-5 ls-2">강아지 정보
                        </h6>
                        <p class="mb-0">예비 견주입니다.</p>
                      </div>
                      <div class="col-6">
                        <h6 class="text-uppercase fs-5 ls-2">이메일 </h6>
                        <p class="mb-0">{{ user.email }}</p>
                      </div>
                      <div class="col-6">
                        <h6 class="text-uppercase fs-5 ls-2">활동 지역
                        </h6>
                        <p class="mb-0">{{ user.address }}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-12 mb-6">
                <!-- card -->
                <div class="card">
                  <!-- card body -->
                  <div class="card-body">
                    <!-- card title -->
                    <h4 class="card-title mb-4">산책 리뷰</h4>
                    {% if review_list %}
                    {% for review in review_list %}
                    <div class="d-flex mb-5">
                      <!-- img -->
                      <div>
                        <img src="{{ review.author.avatar }}" class="rounded-circle avatar-md" alt="">
                      </div>
                      <!-- content -->
                      <div class="ms-3 ">
                        <h5 class="mb-1">{{ review.author.username }}</h5>
                        <p class="text-muted mb-2">{{ review.review }}
                        </p>
                          {% if free.created_string == False %}
                            <p class="fs-5 mb-0">{{ review.created_date|date:'m월 d일' }}</p>
                            {% else %}
                            <p class="fs-5 mb-0">{{ review.created_string }}</p>
                          {% endif %}
                      </div>
                    </div>
                      {% endfor %}
                      {% endif %}
                      <form action="/profile/" method="post" id="review-create" enctype="multipart/form-data">
                          {% csrf_token %}
                            <div class="input-group  mb-3">
                              <input name="review" form="review-create" class="form-control" style="height: 3em;" placeholder="리뷰를 남겨주세요." aria-label="산책 리뷰" aria-describedby="button-addon2">
                              <button class="btn btn-outline-secondary" style="height: 3em;" type="submit" id="button-addon2">남기기</button>
                            </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              <!-- 포스팅 -->
              <div class="row row-cols-1 row-cols-md-3 g-4">
                  {% for post in post_list %}

                  <div class="col">
                      <a href="/blog/post/{{ post.id }}/">
                    <div class="card">
                        <div class="embed-responsive embed-responsive-4by3">
                        {% if post.head_image %}
                        <img src="{{ post.head_image.url }}" class="card-img-top embed-responsive-item" alt="Image">
                        {% else %}
                        <img src="{% static 'blog/img/noimg.jpg' %}" class="card-img-top embed-responsive-item" alt="No image">
                        {% endif %}
                        </div>
                    <div class="card-body">
                        <p class="card-title text-center"> {{ post.title }}</p>
                    </div>
                  </div>
                      </a>
                  </div>

                {% endfor %}
                </div>
              </div>
        </div>
      </div>
{% endblock content %}